[platformio]
src_dir = .

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino
monitor_speed = 115200

; Change upload_port to the COM port of your HEADBAND ESP32
; e.g. upload_port = COM5
; Leave blank to let PlatformIO auto-detect
