[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino
src_dir    = .
monitor_speed = 115200

; Change upload_port to the COM port of your DONGLE ESP32
; e.g. upload_port = COM4
; Leave blank to let PlatformIO auto-detect
